import './Employee.css';
import Card from '../../components/Card/Card.js';
import Table from '../../components/Table/Table.js';

export default function Employee(root) {
  const table = new Table({
    headers: ['사원번호', '이름', '부서', '직급', '이메일', '전화번호'],
    data: employee.map((emp) => [
      `77${emp.userId}`,
      `<img src="${emp.img}" class="thumbnail" > ${emp.name}`,
      emp.dept,
      emp.position,
      emp.email,
      emp.phone,
    ]),
    classList: 'table_employee',
  });

  const card = new Card({
    page: {
      title: '휴가/외출 관리',
      searchArea: true,
      content: `
        <div>${table.render()}</div>
        `,
    },
  });

  root.innerHTML = `<div>
  ${card.render()}
  </div>
  `;
}

// DB 샘플
const employee = [
  {
    userId: '001',
    name: '박보검',
    position: '대표',
    email: 'ceo@77cm.com',
    password: 'CEO12345',
    phone: '010-7107-6358',
    birth: '1980-02-16',
    dept: 'C-level',
    leftVaca: '13일',
    admin: false,
    joinDate: null,
    img: 'http://img.nowon.store/profile/001.jpg',
  },
  {
    userId: '002',
    name: '김대영',
    position: '부장',
    email: 'nyun@77cm.com',
    password: '7SnBRP9a',
    phone: '010-4756-2128',
    birth: '1959-03-04',
    dept: '영업팀',
    leftVaca: '3일',
    admin: false,
    joinDate: null,
    img: 'http://img.nowon.store/profile/002.jpg',
  },
  {
    userId: '003',
    name: '배하은',
    position: '과장',
    email: 'mineunyeong@77cm.com',
    password: '50TslBc3',
    phone: '010-2767-9609',
    birth: '1986-12-21',
    dept: '인사팀',
    leftVaca: '9일',
    admin: false,
    joinDate: null,
    img: 'http://img.nowon.store/profile/003.jpg',
  },
  {
    userId: '004',
    name: '송진',
    position: '대리',
    email: 'gimjunyeong@77cm.com',
    password: 'ZuM6Qr6i',
    phone: '010-9687-8227',
    birth: '1955-03-02',
    dept: '개발팀',
    leftVaca: '1일',
    admin: false,
    joinDate: null,
    img: 'http://img.nowon.store/profile/004.jpg',
  },
  {
    userId: '005',
    name: '박지영',
    position: '차장',
    email: 'seoyeonbag@77cm.com',
    password: 'Q1YRZWgN',
    phone: '010-4344-9545',
    birth: '1996-11-04',
    dept: '개발팀',
    leftVaca: '9일',
    admin: false,
    joinDate: null,
    img: 'http://img.nowon.store/profile/005.jpg',
  },
  {
    userId: '006',
    name: '김해민',
    position: '대리',
    email: 'ni@77cm.com',
    password: '6Flj6fwI',
    phone: '010-1606-4149',
    birth: '1994-01-02',
    dept: '개발팀',
    leftVaca: '3일',
    admin: true,
    joinDate: null,
    img: 'http://img.nowon.store/profile/006.jpg',
  },
  {
    userId: '007',
    name: '유현수',
    position: '차장',
    email: 'seojunbag@77cm.com',
    password: 'z85RpnyD',
    phone: '010-6440-7770',
    birth: '1962-04-08',
    dept: '마케팅팀',
    leftVaca: '17일',
    admin: true,
    joinDate: null,
    img: 'http://img.nowon.store/profile/007.jpg',
  },
  {
    userId: '008',
    name: '김민채',
    position: '대리',
    email: 'hayun94@77cm.com',
    password: '1aSMpkBs',
    phone: '010-4119-4551',
    birth: '2003-08-19',
    dept: '마케팅팀',
    leftVaca: '3일',
    admin: false,
    joinDate: null,
    img: 'http://img.nowon.store/profile/008.jpg',
  },
  {
    userId: '009',
    name: '이규성',
    position: '과장',
    email: 'osugja@77cm.com',
    password: '4NUPD6Ll',
    phone: '010-4464-3177',
    birth: '1962-09-18',
    dept: '인사팀',
    leftVaca: '3일',
    admin: true,
    joinDate: null,
    img: 'http://img.nowon.store/profile/009.jpg',
  },
  {
    userId: '010',
    name: '시아준수',
    position: '대리',
    email: 'hyeonjubag@77cm.com',
    password: 'c33LaWLU',
    phone: '010-3458-3972',
    birth: '1955-06-24',
    dept: '재무팀',
    leftVaca: '9일',
    admin: false,
    joinDate: null,
    img: 'http://img.nowon.store/profile/010.jpg',
  },
  {
    userId: '011',
    name: '이수영',
    position: '대리',
    email: 'hayungim@77cm.com',
    password: 'o5CtMasb',
    phone: '010-3772-4380',
    birth: '1962-03-30',
    dept: '개발팀',
    leftVaca: '19일',
    admin: false,
    joinDate: null,
    img: 'http://img.nowon.store/profile/011.jpg',
  },
  {
    userId: '012',
    name: '장선영',
    position: '부장',
    email: 'jeonghoseo@77cm.com',
    password: 'RKn3lXnp',
    phone: '010-9672-4406',
    birth: '1958-01-22',
    dept: '마케팅팀',
    leftVaca: '4일',
    admin: true,
    joinDate: null,
    img: 'http://img.nowon.store/profile/012.jpg',
  },
  {
    userId: '013',
    name: '이미숙',
    position: 'CTO',
    email: 'anjunyeong@77cm.com',
    password: 'sqf1fqEj',
    phone: '010-2594-5588',
    birth: '1992-10-12',
    dept: 'C-level',
    leftVaca: '12일',
    admin: true,
    joinDate: null,
    img: 'http://img.nowon.store/profile/013.jpg',
  },
  {
    userId: '014',
    name: '허지우',
    position: '사원',
    email: 'egim@77cm.com',
    password: 'v2ERt9LD',
    phone: '010-3615-1216',
    birth: '1992-07-07',
    dept: '영업팀',
    leftVaca: '15일',
    admin: true,
    joinDate: null,
    img: 'http://img.nowon.store/profile/014.jpg',
  },
  {
    userId: '015',
    name: '나현숙',
    position: '대리',
    email: 'seohyeon93@77cm.com',
    password: '7HSYnwSg',
    phone: '010-2130-7575',
    birth: '1980-06-24',
    dept: '개발팀',
    leftVaca: '6일',
    admin: true,
    joinDate: null,
    img: 'http://img.nowon.store/profile/015.jpg',
  },
  {
    userId: '016',
    name: '문상훈',
    position: '사원',
    email: 'yunyeweon@77cm.com',
    password: 'Om7R9dyu',
    phone: '010-504-2283',
    birth: '1977-07-02',
    dept: '인사팀',
    leftVaca: '18일',
    admin: true,
    joinDate: null,
    img: 'http://img.nowon.store/profile/016.jpg',
  },
  {
    userId: '017',
    name: '선우정아',
    position: '대리',
    email: 'caeweoncoe@77cm.com',
    password: '3Te2Mq7p',
    phone: '010-7498-3547',
    birth: '1984-08-20',
    dept: '영업팀',
    leftVaca: '13일',
    admin: false,
    joinDate: null,
    img: 'http://img.nowon.store/profile/017.jpg',
  },
  {
    userId: '018',
    name: '강준호',
    position: '과장',
    email: 'sanghun89@77cm.com',
    password: '3DlebUnL',
    phone: '010-4197-3243',
    birth: '1998-01-09',
    dept: '재무팀',
    leftVaca: '3일',
    admin: false,
    joinDate: null,
    img: 'http://img.nowon.store/profile/018.jpg',
  },
  {
    userId: '019',
    name: '차민지',
    position: '부장',
    email: 'ngim@77cm.com',
    password: '0AOEn1jR',
    phone: '010-9593-5475',
    birth: '1978-10-20',
    dept: '개발팀',
    leftVaca: '15일',
    admin: true,
    joinDate: null,
    img: 'http://img.nowon.store/profile/019.jpg',
  },
  {
    userId: '020',
    name: '나주원',
    position: '대리',
    email: 'xjeon@77cm.com',
    password: 'Hb9tAYrf',
    phone: '010-6799-2799',
    birth: '1961-11-17',
    dept: '개발팀',
    leftVaca: '19일',
    admin: false,
    joinDate: null,
    img: 'http://img.nowon.store/profile/020.jpg',
  },
  {
    userId: '021',
    name: '박서현',
    position: '과장',
    email: 'bagminjun@77cm.com',
    password: 'u3I0MQCw',
    phone: '010-5853-7865',
    birth: '1995-09-05',
    dept: '인사팀',
    leftVaca: '6일',
    admin: true,
    joinDate: null,
    img: 'http://img.nowon.store/profile/021.jpg',
  },
  {
    userId: '022',
    name: '이미숙',
    position: 'COO',
    email: 'wgo@77cm.com',
    password: '4XaxgV3v',
    phone: '010-4765-6954',
    birth: '1975-10-28',
    dept: 'C-level',
    leftVaca: '11일',
    admin: false,
    joinDate: null,
    img: 'http://img.nowon.store/profile/022.jpg',
  },
  {
    userId: '023',
    name: '고미경',
    position: '부장',
    email: 'xryu@77cm.com',
    password: '1WUWrJIi',
    phone: '010-4470-9567',
    birth: '1973-07-21',
    dept: '마케팅팀',
    leftVaca: '12일',
    admin: false,
    joinDate: null,
    img: 'http://img.nowon.store/profile/023.jpg',
  },
  {
    userId: '024',
    name: '이지은',
    position: '차장',
    email: 'tgang@77cm.com',
    password: 'bK0E4Rzv',
    phone: '010-2778-8439',
    birth: '1976-08-17',
    dept: '개발팀',
    leftVaca: '4일',
    admin: true,
    joinDate: null,
    img: 'http://img.nowon.store/profile/024.jpg',
  },
  {
    userId: '025',
    name: '김성민',
    position: '차장',
    email: 'yi@77cm.com',
    password: '7CiJSDWt',
    phone: '010-1441-3557',
    birth: '1996-08-25',
    dept: '개발팀',
    leftVaca: '13일',
    admin: false,
    joinDate: null,
    img: 'http://img.nowon.store/profile/025.jpg',
  },
  {
    userId: '026',
    name: '박건우',
    position: '차장',
    email: 'boram86@77cm.com',
    password: 'fn3v8Zac',
    phone: '010-8324-6723',
    birth: '1989-10-18',
    dept: '인사팀',
    leftVaca: '6일',
    admin: true,
    joinDate: null,
    img: 'http://img.nowon.store/profile/026.jpg',
  },
  {
    userId: '027',
    name: '박순옥',
    position: '차장',
    email: 'goyeongmi@77cm.com',
    password: '0GD42Eon',
    phone: '010-8214-6136',
    birth: '1990-06-29',
    dept: '개발팀',
    leftVaca: '11일',
    admin: false,
    joinDate: null,
    img: 'http://img.nowon.store/profile/027.jpg',
  },
  {
    userId: '028',
    name: '김명숙',
    position: '부장',
    email: 'myeongsuggim@77cm.com',
    password: '0Zm5SsO',
    phone: '010-5034-2892',
    birth: '1989-04-06',
    dept: '재무팀',
    leftVaca: '4일',
    admin: false,
    joinDate: null,
    img: 'http://img.nowon.store/profile/028.jpg',
  },
  {
    userId: '029',
    name: '이명숙',
    position: '과장',
    email: 'seojun87@77cm.com',
    password: 'H2K6RKyu',
    phone: '010-9739-3409',
    birth: '1988-11-10',
    dept: '재무팀',
    leftVaca: '10일',
    admin: true,
    joinDate: null,
    img: 'http://img.nowon.store/profile/029.jpg',
  },
  {
    userId: '030',
    name: '송건우',
    position: '부장',
    email: 'yejingim@77cm.com',
    password: 'ScN8AhM1',
    phone: '010-5689-5619',
    birth: '1978-07-05',
    dept: '영업팀',
    leftVaca: '6일',
    admin: true,
    joinDate: null,
    img: 'http://img.nowon.store/profile/030.jpg',
  },
  {
    userId: '031',
    name: '김영수',
    position: '사원',
    email: 'ujinhan@77cm.com',
    password: 'On7o2NFv',
    phone: '010-9481-7783',
    birth: '1992-08-12',
    dept: '재무팀',
    leftVaca: '7일',
    admin: true,
    joinDate: null,
    img: 'http://img.nowon.store/profile/031.jpg',
  },
  {
    userId: '032',
    name: '김진우',
    position: '차장',
    email: 'ieunyeong@77cm.com',
    password: 'pR1ztAgw',
    phone: '010-4796-9810',
    birth: '1967-05-20',
    dept: '인사팀',
    leftVaca: '9일',
    admin: false,
    joinDate: null,
    img: 'http://img.nowon.store/profile/032.jpg',
  },
  {
    userId: '033',
    name: '김순옥',
    position: '대리',
    email: 'syun@77cm.com',
    password: 'Gce1RskH',
    phone: '010-3850-2513',
    birth: '1996-06-25',
    dept: '개발팀',
    leftVaca: '7일',
    admin: true,
    joinDate: null,
    img: 'http://img.nowon.store/profile/033.jpg',
  },
  {
    userId: '034',
    name: '이명자',
    position: '차장',
    email: 'msin@77cm.com',
    password: 'h0JP5hGE',
    phone: '010-5461-1126',
    birth: '1990-08-30',
    dept: '마케팅팀',
    leftVaca: '18일',
    admin: true,
    joinDate: null,
    img: 'http://img.nowon.store/profile/034.jpg',
  },
  {
    userId: '035',
    name: '차준호',
    position: '과장',
    email: 'seungmin66@77cm.com',
    password: '4WILRuEe',
    phone: '010-9212-3988',
    birth: '1987-07-31',
    dept: '개발팀',
    leftVaca: '13일',
    admin: true,
    joinDate: null,
    img: 'http://img.nowon.store/profile/035.jpg',
  },
  {
    userId: '036',
    name: '김채원',
    position: '대리',
    email: 'jangsugja@77cm.com',
    password: '86MQEGbj',
    phone: '010-4393-2348',
    birth: '1982-05-21',
    dept: '마케팅팀',
    leftVaca: '20일',
    admin: false,
    joinDate: null,
    img: 'http://img.nowon.store/profile/036.jpg',
  },
  {
    userId: '037',
    name: '김영식',
    position: 'CHO',
    email: 'yunjunho@77cm.com',
    password: 'CgU32Myw',
    phone: '010-7859-1096',
    birth: '1979-06-03',
    dept: 'C-level',
    leftVaca: '0일',
    admin: false,
    joinDate: null,
    img: 'http://img.nowon.store/profile/037.jpg',
  },
  {
    userId: '038',
    name: '전영환',
    position: '차장',
    email: 'isangceol@77cm.com',
    password: '6GtqDzDp',
    phone: '010-3573-6983',
    birth: '1965-08-14',
    dept: '마케팅팀',
    leftVaca: '8일',
    admin: true,
    joinDate: null,
    img: 'http://img.nowon.store/profile/038.jpg',
  },
  {
    userId: '039',
    name: '류은지',
    position: '대리',
    email: 'hwangareum@77cm.com',
    password: '2mySwyg9',
    phone: '010-3290-8158',
    birth: '1974-08-14',
    dept: '개발팀',
    leftVaca: '17일',
    admin: true,
    joinDate: null,
    img: 'http://img.nowon.store/profile/039.jpg',
  },
  {
    userId: '040',
    name: '허영진',
    position: '차장',
    email: 'caeweonji@77cm.com',
    password: 'jv5vOQb8',
    phone: '010-5350-8026',
    birth: '1971-01-10',
    dept: '개발팀',
    leftVaca: '16일',
    admin: false,
    joinDate: null,
    img: 'http://img.nowon.store/profile/040.jpg',
  },
  {
    userId: '041',
    name: '최은지',
    position: 'CFO',
    email: 'rgim@77cm.com',
    password: '3OU0Veci',
    phone: '010-4794-3458',
    birth: '1996-05-03',
    dept: 'C-level',
    leftVaca: '10일',
    admin: false,
    joinDate: null,
    img: 'http://img.nowon.store/profile/041.jpg',
  },
  {
    userId: '042',
    name: '임지훈',
    position: '사원',
    email: 'si@77cm.com',
    password: 'w91pH0Gd',
    phone: '010-6460-5331',
    birth: '1956-08-20',
    dept: '재무팀',
    leftVaca: '10일',
    admin: false,
    joinDate: null,
    img: 'http://img.nowon.store/profile/042.jpg',
  },
  {
    userId: '043',
    name: '김은주',
    position: '과장',
    email: 'vbag@77cm.com',
    password: 'Tn9TTvLj',
    phone: '010-8430-8897',
    birth: '1974-07-11',
    dept: '인사팀',
    leftVaca: '20일',
    admin: true,
    joinDate: null,
    img: 'http://img.nowon.store/profile/043.jpg',
  },
  {
    userId: '044',
    name: '김서연',
    position: '사원',
    email: 'sunja80@77cm.com',
    password: 'J4jM4VSp',
    phone: '010-2434-8517',
    birth: '1964-11-02',
    dept: '인사팀',
    leftVaca: '10일',
    admin: true,
    joinDate: null,
    img: 'http://img.nowon.store/profile/044.jpg',
  },
  {
    userId: '045',
    name: '김승현',
    position: '대리',
    email: 'gimyeeun@77cm.com',
    password: '0my6Pcmc',
    phone: '010-5555-2735',
    birth: '1966-06-19',
    dept: '인사팀',
    leftVaca: '14일',
    admin: false,
    joinDate: null,
    img: 'http://img.nowon.store/profile/045.jpg',
  },
  {
    userId: '046',
    name: '박상호',
    position: '사원',
    email: 'jia30@77cm.com',
    password: 'yfH9Up4n',
    phone: '010-2516-5342',
    birth: '1986-05-01',
    dept: '마케팅팀',
    leftVaca: '4일',
    admin: true,
    joinDate: null,
    img: 'http://img.nowon.store/profile/046.jpg',
  },
  {
    userId: '047',
    name: '박옥순',
    position: '부장',
    email: 'coegyeongja@77cm.com',
    password: 'kb29MDup',
    phone: '010-6028-3294',
    birth: '1957-10-17',
    dept: '마케팅팀',
    leftVaca: '13일',
    admin: true,
    joinDate: null,
    img: 'http://img.nowon.store/profile/047.jpg',
  },
  {
    userId: '048',
    name: '김민재',
    position: '차장',
    email: 'myeongjanam@77cm.com',
    password: 'o9WPJaFH',
    phone: '010-5668-3822',
    birth: '1996-03-04',
    dept: '개발팀',
    leftVaca: '15일',
    admin: false,
    joinDate: null,
    img: 'http://img.nowon.store/profile/048.jpg',
  },
  {
    userId: '049',
    name: '박정남',
    position: '대리',
    email: 'gimareum@77cm.com',
    password: '6KKVzXAa',
    phone: '010-2862-7517',
    birth: '1954-01-31',
    dept: '재무팀',
    leftVaca: '14일',
    admin: false,
    joinDate: null,
    img: 'http://img.nowon.store/profile/049.jpg',
  },
  {
    userId: '050',
    name: '진정남',
    position: '차장',
    email: 'heoeungyeong@77cm.com',
    password: 'TP35sPo7',
    phone: '010-7346-9942',
    birth: '1958-08-04',
    dept: '인사팀',
    leftVaca: '8일',
    admin: true,
    joinDate: null,
    img: 'http://img.nowon.store/profile/050.jpg',
  },
  {
    userId: '051',
    name: '박광수',
    position: '부장',
    email: 'tjeong@77cm.com',
    password: 'lY3tMTjv',
    phone: '010-7053-7343',
    birth: '1972-05-28',
    dept: '인사팀',
    leftVaca: '19일',
    admin: false,
    joinDate: null,
    img: 'http://img.nowon.store/profile/default.png',
  },
  {
    userId: '052',
    name: '이정훈',
    position: '부장',
    email: 'bi@77cm.com',
    password: 'k9yVn4gC',
    phone: '010-4796-6827',
    birth: '1966-03-20',
    dept: '인사팀',
    leftVaca: '16일',
    admin: true,
    joinDate: null,
    img: 'http://img.nowon.store/profile/default.png',
  },
  {
    userId: '053',
    name: '김지연',
    position: '과장',
    email: 'gimmiyeong@77cm.com',
    password: '5KIpsVfH',
    phone: '010-4153-7263',
    birth: '1967-05-09',
    dept: '마케팅팀',
    leftVaca: '6일',
    admin: false,
    joinDate: null,
    img: 'http://img.nowon.store/profile/default.png',
  },
  {
    userId: '054',
    name: '김진우',
    position: '차장',
    email: 'yujin09@77cm.com',
    password: 'J317pQhw',
    phone: '010-4282-3310',
    birth: '1988-01-07',
    dept: '마케팅팀',
    leftVaca: '9일',
    admin: true,
    joinDate: null,
    img: 'http://img.nowon.store/profile/default.png',
  },
  {
    userId: '055',
    name: '송지훈',
    position: '사원',
    email: 'jihyeon56@77cm.com',
    password: 'WHpM8Nqg',
    phone: '010-1992-4763',
    birth: '1963-10-20',
    dept: '개발팀',
    leftVaca: '13일',
    admin: false,
    joinDate: null,
    img: 'http://img.nowon.store/profile/default.png',
  },
  {
    userId: '056',
    name: '김승현',
    position: '부장',
    email: 'misuggo@77cm.com',
    password: '9mPHNCqK',
    phone: '010-4603-6641',
    birth: '1996-07-28',
    dept: '마케팅팀',
    leftVaca: '6일',
    admin: true,
    joinDate: null,
    img: 'http://img.nowon.store/profile/default.png',
  },
  {
    userId: '057',
    name: '오정식',
    position: '부장',
    email: 'jeongho04@77cm.com',
    password: 'x2WpV6Id',
    phone: '010-5734-4126',
    birth: '1964-08-12',
    dept: '마케팅팀',
    leftVaca: '0일',
    admin: true,
    joinDate: null,
    img: 'http://img.nowon.store/profile/default.png',
  },
  {
    userId: '058',
    name: '이수민',
    position: '과장',
    email: 'sanghyeon41@77cm.com',
    password: 'PkRTA1Bh',
    phone: '010-3148-6023',
    birth: '1987-10-24',
    dept: '영업팀',
    leftVaca: '16일',
    admin: false,
    joinDate: null,
    img: 'http://img.nowon.store/profile/default.png',
  },
  {
    userId: '059',
    name: '손정희',
    position: '대리',
    email: 'jeongja41@77cm.com',
    password: '4XyakaXx',
    phone: '010-4947-1414',
    birth: '1964-09-05',
    dept: '마케팅팀',
    leftVaca: '2일',
    admin: false,
    joinDate: null,
    img: 'http://img.nowon.store/profile/default.png',
  },
  {
    userId: '060',
    name: '서주원',
    position: '차장',
    email: 'gimmyeongsug@77cm.com',
    password: '1FkntKgk',
    phone: '010-2754-6715',
    birth: '1984-07-25',
    dept: '마케팅팀',
    leftVaca: '15일',
    admin: true,
    joinDate: null,
    img: 'http://img.nowon.store/profile/default.png',
  },
  {
    userId: '061',
    name: '양현주',
    position: '차장',
    email: 'seunghyeon15@77cm.com',
    password: '0aTW9HTt',
    phone: '010-4125-2285',
    birth: '1959-01-20',
    dept: '영업팀',
    leftVaca: '4일',
    admin: false,
    joinDate: null,
    img: 'http://img.nowon.store/profile/default.png',
  },
  {
    userId: '062',
    name: '김은영',
    position: '차장',
    email: 'mgim@77cm.com',
    password: 'GO2l4XbI',
    phone: '010-6939-3328',
    birth: '1963-01-16',
    dept: '마케팅팀',
    leftVaca: '14일',
    admin: true,
    joinDate: null,
    img: 'http://img.nowon.store/profile/default.png',
  },
  {
    userId: '063',
    name: '이현우',
    position: '대리',
    email: 'seohyeon77@77cm.com',
    password: '9SuGVPym',
    phone: '010-5773-4721',
    birth: '1979-11-30',
    dept: '마케팅팀',
    leftVaca: '13일',
    admin: false,
    joinDate: null,
    img: 'http://img.nowon.store/profile/default.png',
  },
  {
    userId: '064',
    name: '허성수',
    position: '차장',
    email: 'minjunhan@77cm.com',
    password: 'yo4Sz0Vr',
    phone: '010-3324-7576',
    birth: '1960-02-19',
    dept: '인사팀',
    leftVaca: '17일',
    admin: false,
    joinDate: null,
    img: 'http://img.nowon.store/profile/default.png',
  },
  {
    userId: '065',
    name: '이수민',
    position: '사원',
    email: 'seonghunno@77cm.com',
    password: '7QEuhVvT',
    phone: '010-5984-4826',
    birth: '1984-09-01',
    dept: '영업팀',
    leftVaca: '9일',
    admin: false,
    joinDate: null,
    img: 'http://img.nowon.store/profile/default.png',
  },
  {
    userId: '066',
    name: '이예원',
    position: '사원',
    email: 'soncunja@77cm.com',
    password: 'vl9RcZd7',
    phone: '010-705-2729',
    birth: '1980-09-29',
    dept: '영업팀',
    leftVaca: '13일',
    admin: true,
    joinDate: null,
    img: 'http://img.nowon.store/profile/default.png',
  },
  {
    userId: '067',
    name: '고현주',
    position: '대리',
    email: 'seongsu66@77cm.com',
    password: 'q3U9Q2Xu',
    phone: '010-1902-9125',
    birth: '1979-04-20',
    dept: '마케팅팀',
    leftVaca: '9일',
    admin: true,
    joinDate: null,
    img: 'http://img.nowon.store/profile/default.png',
  },
];
